SELECT *
FROM dim.occasionsurvey;

CALL dim.usp_refresh_occasionsurvey();

-- Table: dim.occasionsurvey

-- DROP TABLE IF EXISTS dim.occasionsurvey;

CREATE TABLE IF NOT EXISTS dim.occasionsurvey
(
    surveykey bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    organizationid text COLLATE pg_catalog."default" NOT NULL,
    surveyid text COLLATE pg_catalog."default" NOT NULL,
    surveyname text COLLATE pg_catalog."default",
    surveytype INTEGER,
    question_type integer,
    selection_type integer,
    survey_status integer,
    is_deleted boolean,
    created_on timestamp without time zone,
    modified_on timestamp without time zone,
    sysinserttime timestamp without time zone,
    sysupdatetime timestamp without time zone,
    CONSTRAINT survey_pkey PRIMARY KEY (surveykey),
    CONSTRAINT orgid_surveyid_pk UNIQUE (organizationid, surveyid)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS dim.occasionsurvey
    OWNER to citus;

--DROP TABLE IF EXISTS stg.dim_occasionsurvey;
CREATE TABLE IF NOT EXISTS stg.dim_occasionsurvey
(
    organizationid text COLLATE pg_catalog."default" NOT NULL,
    surveyid text COLLATE pg_catalog."default" NOT NULL,
    surveyname text COLLATE pg_catalog."default",
    surveytype INTEGER,
    question_type integer,
    selection_type integer,
    survey_status integer,
    is_deleted boolean,
    created_on timestamp without time zone,
    modified_on timestamp without time zone,
    sysinserttime timestamp without time zone
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS stg.dim_occasionsurvey
    OWNER to citus;


-- Index: organizationid_idx

-- DROP INDEX IF EXISTS dim.organizationid_idx;

CREATE INDEX IF NOT EXISTS organizationid_idx
    ON dim.occasionsurvey USING btree
    (organizationid COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: surveyid_idx

-- DROP INDEX IF EXISTS dim.surveyid_idx;

CREATE INDEX IF NOT EXISTS surveyid_idx
    ON dim.occasionsurvey USING btree
    (surveyid COLLATE pg_catalog."default" ASC NULLS LAST)
    INCLUDE(surveyname, surveytype)
    TABLESPACE pg_default;



-- ============================================================
-- dim.occasionsurvey  –  Refresh Procedure
-- Source:  stg.dim_occasionsurvey  (via ADF Copy Activity)
-- Target:  dim.occasionsurvey
-- Natural key / UNIQUE : (organizationid, surveyid)
-- Surrogate key: surveykey BIGINT – manual sequence (DWH standard)
-- ============================================================


-- ============================================================
-- SECTION 1 – MIGRATE FROM IDENTITY TO SEQUENCE (one-time)
-- Drops the identity property and attaches a standard sequence
-- synced to the current max surveykey value.
-- ============================================================

-- Step 1a: drop the identity property, keep existing values
ALTER TABLE IF EXISTS dim.occasionsurvey
    ALTER COLUMN surveykey DROP IDENTITY IF EXISTS;

ALTER TABLE IF EXISTS dim.occasionsurvey
    ALTER COLUMN surveytype TYPE INTEGER USING surveytype::INTEGER;

-- Step 1b: create the sequence
CREATE SEQUENCE IF NOT EXISTS dim.occasionsurvey_surveykey_seq;

-- Step 1c: sync sequence to current max to avoid collisions
SELECT setval(
    'dim.occasionsurvey_surveykey_seq',
    COALESCE((SELECT MAX(surveykey) FROM dim.occasionsurvey), 0)
);

-- Step 1d: attach sequence as column default
ALTER TABLE dim.occasionsurvey
    ALTER COLUMN surveykey SET DEFAULT nextval('dim.occasionsurvey_surveykey_seq');


-- ============================================================
-- SECTION 2 – REFRESH STORED PROCEDURE
-- ============================================================

CREATE OR REPLACE PROCEDURE dim.usp_refresh_occasionsurvey()
LANGUAGE plpgsql
AS $BODY$
BEGIN

    -- ── Step 1: deduplicate staging ───────────────────────────
    CREATE TEMP TABLE tmp_occasionsurvey ON COMMIT DROP AS
    SELECT DISTINCT ON (organizationid, surveyid)
        organizationid,
        surveyid,
        surveyname,
        surveytype,
        question_type,
        selection_type,
        survey_status,
        is_deleted,
        created_on,
        modified_on
    FROM stg.dim_occasionsurvey
    ORDER BY organizationid, surveyid, modified_on DESC NULLS LAST;

    CREATE INDEX ix_tmp_occasionsurvey
        ON tmp_occasionsurvey (organizationid, surveyid);
    ANALYZE tmp_occasionsurvey;

    -- ── Step 2: INSERT net-new surveys ────────────────────────
    INSERT INTO dim.occasionsurvey (
        surveykey,
        organizationid,
        surveyid,
        surveyname,
        surveytype,
        question_type,
        selection_type,
        survey_status,
        is_deleted,
        created_on,
        modified_on,
        sysinserttime
    )
    SELECT
        nextval('dim.occasionsurvey_surveykey_seq'),
        t.organizationid,
        t.surveyid,
        t.surveyname,
        t.surveytype,
        t.question_type,
        t.selection_type,
        t.survey_status,
        t.is_deleted,
        t.created_on,
        t.modified_on,
        NOW()
    FROM tmp_occasionsurvey t
    WHERE NOT EXISTS (
        SELECT 1 FROM dim.occasionsurvey d
        WHERE d.organizationid = t.organizationid
          AND d.surveyid       = t.surveyid
    );

    -- ── Step 3: UPDATE changed attributes ────────────────────
    -- Only fires when at least one mutable column has changed.
    UPDATE dim.occasionsurvey d
    SET
        surveyname     = t.surveyname,
        surveytype     = t.surveytype,
        question_type  = t.question_type,
        selection_type = t.selection_type,
        survey_status  = t.survey_status,
        is_deleted     = t.is_deleted,
        created_on     = t.created_on,
        modified_on    = t.modified_on,
        sysupdatetime  = NOW()
    FROM tmp_occasionsurvey t
    WHERE d.organizationid = t.organizationid
      AND d.surveyid       = t.surveyid
      AND (
          d.surveyname     IS DISTINCT FROM t.surveyname     OR
          d.surveytype     IS DISTINCT FROM t.surveytype     OR
          d.question_type  IS DISTINCT FROM t.question_type  OR
          d.selection_type IS DISTINCT FROM t.selection_type OR
          d.survey_status  IS DISTINCT FROM t.survey_status  OR
          d.is_deleted     IS DISTINCT FROM t.is_deleted     OR
          d.created_on     IS DISTINCT FROM t.created_on     OR
          d.modified_on    IS DISTINCT FROM t.modified_on
      );

END;
$BODY$;

ALTER PROCEDURE dim.usp_refresh_occasionsurvey()
    OWNER TO citus;


-- ============================================================
-- Source query (for ADF Copy Activity reference)
-- ISO timestamp parsing handled by ADF on copy to stg
-- ============================================================
-- SELECT DISTINCT
--        c.organizationId  AS organizationid,
--        c.surveyId        AS surveyid,
--        c.name            AS surveyname,
--        c.surveyType      AS surveytype,
--        c.questionType    AS question_type,
--        c.selectionType   AS selection_type,
--        c.status          AS survey_status,
--        c.isDeleted       AS is_deleted,
--        c.createdOn       AS created_on,
--        c.modifiedOn      AS modified_on,
--        NOW()::TIMESTAMP  AS sysinserttime
-- FROM survey AS c