CREATE TABLE IF NOT EXISTS dim.kiosk
(
    id bigint NOT NULL,
    locationid text COLLATE pg_catalog."default" NOT NULL,
    kioskid text COLLATE pg_catalog."default" NOT NULL,
    kioskname text COLLATE pg_catalog."default",
    serialnumber text COLLATE pg_catalog."default",
    appversion text COLLATE pg_catalog."default",
    istestkiosk boolean,
    devicetype character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'kiosk'::character varying,
    devicecreatedon timestamp without time zone,
    devicedeletedon timestamp without time zone,
    CONSTRAINT kiosk_pk PRIMARY KEY (id),
    CONSTRAINT kiosk_uidx UNIQUE (locationid, kioskid)
)

TABLESPACE pg_default;

ALTER TABLE dim.kiosk
    OWNER to citus;


-- Index: dim.kiosk_location_idx
CREATE INDEX IF NOT EXISTS kiosk_location_idx
    ON dim.kiosk USING btree
    (locationid COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

--insert into dim.kiosk(locationid, kioskid, kioskname, serialnumber, appversion, istestkiosk)
select locationid, kioskid, kioskname, serialnumber, appversion, istestkiosk 
from dim.kiosk_bkp

select * from dim.kiosk_bkp
select * from dim.kiosk

ALTER TABLE dim.kiosk
alter column id
--drop IDENTITY
--add GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 );

ALTER TABLE dim.kiosk
--drop COLUMN devicedeletedon
--add devicecreatedon TIMESTAMP
add devicedeletedon TIMESTAMP

SELECT * from dim.device