--New table in all environments
--drop table if EXISTS dim.occasionsurvey;
CREATE TABLE IF NOT EXISTS dim.occasionsurvey
(
    surveykey bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    organizationid text COLLATE pg_catalog."default" NOT NULL,
    surveyid text COLLATE pg_catalog."default" NOT NULL,
    surveyname text COLLATE pg_catalog."default",
    surveytype text COLLATE pg_catalog."default",
    CONSTRAINT survey_pkey PRIMARY KEY (surveykey)
)
TABLESPACE pg_default;

ALTER TABLE fact.devicetelemetry
    OWNER to citus;
