drop table if exists dim.occasionsurvey;
CREATE TABLE IF NOT EXISTS dim.occasionsurvey
(
    surveykey bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    organizationid text COLLATE pg_catalog."default" NOT NULL,
    surveyid text COLLATE pg_catalog."default" NOT NULL,
    surveyname text COLLATE pg_catalog."default",
    surveytype text COLLATE pg_catalog."default",
    CONSTRAINT survey_pkey PRIMARY KEY (surveykey)
)

TABLESPACE pg_default;

ALTER TABLE dim.occasionsurvey
    OWNER to citus;

--drop table if EXISTS fact.itemssurvey;
CREATE TABLE IF NOT EXISTS fact.itemssurvey
(
    organizationid text COLLATE pg_catalog."default",
    locationid text COLLATE pg_catalog."default",
    dateid integer,
    surveyid text COLLATE pg_catalog."default",
    surveytransid text COLLATE pg_catalog."default",
    orderid text COLLATE pg_catalog."default",
    itemid text COLLATE pg_catalog."default",
    itemrating text COLLATE pg_catalog."default",
    surveytransstatus text COLLATE pg_catalog."default",
    surveyissuedtimestamp text COLLATE pg_catalog."default",
    surveycompletedtimestamp text COLLATE pg_catalog."default",
    surveylocaltimestamp timestamp,
    sysinserttime timestamp
)

TABLESPACE pg_default;

ALTER TABLE fact.itemssurvey
    OWNER to citus;

--drop TABLE IF EXISTS fact.occasionsurveydetail;
CREATE TABLE IF NOT EXISTS fact.occasionsurveydetail
(
    organizationid text COLLATE pg_catalog."default",
    locationid text COLLATE pg_catalog."default",
    dateid integer,
    surveyid text COLLATE pg_catalog."default",
    surveytransid text COLLATE pg_catalog."default",
    orderid text COLLATE pg_catalog."default",
    surveyrating text COLLATE pg_catalog."default",
    surveytransstatus text COLLATE pg_catalog."default",
    surveyissuedtimestamp text COLLATE pg_catalog."default",
    surveycompletedtimestamp text COLLATE pg_catalog."default",
    surveylocaltimestamp timestamp,
    sysinserttime timestamp without time zone
)

TABLESPACE pg_default;

ALTER TRUNCATE TABLE fact.occasionsurveydetail
    OWNER to citus;

-- Table: stg.sent_surveys

-- DROP TABLE IF EXISTS stg.sent_surveys;

CREATE TABLE IF NOT EXISTS stg.sent_surveys
(
    organizationid text COLLATE pg_catalog."default",
    locationid text COLLATE pg_catalog."default" NOT NULL,
    ordersessionid text COLLATE pg_catalog."default" NOT NULL,
    orderid text COLLATE pg_catalog."default",
    gem_event_category text COLLATE pg_catalog."default",
    gem_event_type text COLLATE pg_catalog."default",
    survey_metadata text COLLATE pg_catalog."default",
    is_responded boolean,
    gem_event_instant text COLLATE pg_catalog."default",
    gem_syscosmosts bigint,
    sysinserttime timestamp without time zone,
    sysupdatetime timestamp without time zone,
    CONSTRAINT sent_surveys_ordersessionid_pkey PRIMARY KEY (locationid, ordersessionid)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS stg.sent_surveys
    OWNER to citus;

ALTER TABLE stg.sent_surveys
--ADD COLUMN IF NOT EXISTS orderid TEXT COLLATE pg_catalog."default";
--DROP CONSTRAINT sent_surveys_ordersessionid_pkey
ADD CONSTRAINT sent_surveys_ordersessionid_pkey PRIMARY KEY (locationid, ordersessionid)

CREATE TABLE IF NOT EXISTS fact.sent_surveys
(
    organizationid text COLLATE pg_catalog."default",
    locationid text COLLATE pg_catalog."default" NOT NULL,
    ordersessionid text COLLATE pg_catalog."default" NOT NULL,
    orderid text COLLATE pg_catalog."default",
    gem_event_category text COLLATE pg_catalog."default",
    gem_event_type text COLLATE pg_catalog."default",
    survey_metadata jsonb,
    is_responded boolean,
    gem_event_instant text COLLATE pg_catalog."default",
    gem_syscosmosts bigint,
    sysinserttime timestamp without time zone,
    sysupdatetime timestamp without time zone,
    CONSTRAINT sent_surveys_ordersessionid_pkey PRIMARY KEY (locationid, ordersessionid)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS fact.sent_surveys
    OWNER to citus;

SELECT * FROM fact.itemssurvey

SELECT * FROM stg.sent_surveys

ALTER TABLE fact.occasionsurveydetail
--DROP COLUMN ngesyscosmosts,
--DROP COLUMN gemsyscosmosts
--add syscosmosts BIGINT--- ngesyscosmosts BIGINT, add gemsyscosmosts BIGINT,
ADD COLUMN IF NOT EXISTS surveytype INTEGER, --number-based feedback = 1; text-based feedback = 2
ADD COLUMN IF NOT EXISTS ordersessionid TEXT COLLATE pg_catalog."default"

ALTER TABLE fact.itemssurvey
ADD COLUMN IF NOT EXISTS nge_syscosmosts BIGINT,
ADD COLUMN IF NOT EXISTS ordersessionid TEXT COLLATE pg_catalog."default",
ADD COLUMN IF NOT EXISTS gem_event_category TEXT COLLATE pg_catalog."default",
ADD COLUMN IF NOT EXISTS gem_event_type TEXT COLLATE pg_catalog."default",
ADD COLUMN IF NOT EXISTS is_responded BOOLEAN,
ADD COLUMN IF NOT EXISTS gem_syscosmosts BIGINT,
ADD COLUMN IF NOT EXISTS gem_event_instant TEXT COLLATE pg_catalog."default",
ADD COLUMN IF NOT EXISTS sysupdatetime TIMESTAMP,
ADD COLUMN IF NOT EXISTS sourceid INTEGER;

SELECT orderid, itemid, count(*)
FROM fact.itemssurvey --LIMIT 100
GROUP BY orderid, itemid
HAVING count(*) > 1

SELECT * FROM stg.sent_surveys
SELECT * FROM fact.sent_surveys
SELECT * FROM fact.itemssurvey
SELECT * FROM dim.feedbackstatus

CALL fact.usp_gem_sent_surveys_to_fact();

CREATE OR REPLACE PROCEDURE fact.usp_gem_sent_surveys_to_fact()
LANGUAGE plpgsql
AS $BODY$

BEGIN

INSERT INTO fact.sent_surveys
SELECT
    organizationid,
    locationid,
    ordersessionid,
    orderid,
    gem_event_category,
    gem_event_type,
    survey_metadata :: jsonb as survey_metadata,
    is_responded,
    gem_event_instant,
    gem_syscosmosts,
    sysinserttime,
    sysupdatetime
FROM stg.sent_surveys AS ss
WHERE NOT EXISTS (SELECT 1 FROM fact.sent_surveys as fs 
                  WHERE fs.locationid = ss.locationid 
                    AND fs.ordersessionid = ss.ordersessionid);

UPDATE fact.watermarktable
SET ts = (SELECT coalesce(max(gem_syscosmosts), 1775002010) FROM fact.sent_surveys)
WHERE watermarktablename = 'fact.sent_surveys'
  AND source = 'gem';

END;
$BODY$;


ALTER PROCEDURE fact.usp_gem_sent_surveys_to_fact()
OWNER TO citus;

SELECT * FROM fact.watermarktable;
SELECT * FROM stg.sent_surveys
SELECT * FROM fact.sent_surveys
SELECT * FROM fact.occasionsurveydetail
SELECT * FROM fact.itemssurvey

CALL fact.usp_sent_surveys_to_fact_itemssurvey();

CREATE OR REPLACE PROCEDURE fact.usp_sent_surveys_to_fact_itemssurvey()
LANGUAGE plpgsql
AS $BODY$

BEGIN

DROP TABLE IF EXISTS temp_delta_sent_surveys;
CREATE TEMPORARY TABLE temp_delta_sent_surveys (
    organizationid       TEXT COLLATE pg_catalog."default",
    locationid           TEXT COLLATE pg_catalog."default",
    ordersessionid       TEXT COLLATE pg_catalog."default",
    transactionheaderid  TEXT COLLATE pg_catalog."default",
    gem_event_category   TEXT COLLATE pg_catalog."default",
    gem_event_type       TEXT COLLATE pg_catalog."default",
    orderid              TEXT COLLATE pg_catalog."default",
    surveyid             TEXT COLLATE pg_catalog."default",
    itemid               TEXT COLLATE pg_catalog."default",
    is_responded         BOOLEAN,
    gem_event_instant    TEXT COLLATE pg_catalog."default",
    gem_syscosmosts      BIGINT,
    sysinserttime        TIMESTAMP,
    sysupdatetime        TIMESTAMP,
    menuitemid           TEXT COLLATE pg_catalog."default"
);


WITH delta_sent_surveys AS (
    SELECT 
        organizationid,
        locationid,
        ordersessionid,
        orderid AS transactionheaderid,
        gem_event_category,
        gem_event_type,
        survey_metadata,
        CONCAT('ord-', (survey_metadata ->> 'orderId')::TEXT) AS orderid,
        CASE WHEN jsonb_typeof(survey_metadata -> 'surveyIds') = 'array' THEN survey_metadata -> 'surveyIds' END AS surveyid_array,
        CASE WHEN survey_metadata ->> 'surveyIds' NOT LIKE '[%]' THEN survey_metadata ->> 'surveyIds' END AS surveyid_text,
        CASE WHEN jsonb_typeof(survey_metadata -> 'itemId') = 'array' THEN survey_metadata -> 'itemId' END AS itemid_array,
        CASE WHEN survey_metadata ->> 'itemId' NOT LIKE '[%]' THEN survey_metadata ->> 'itemId' END AS itemid_text,
        is_responded,
        gem_event_instant,
        gem_syscosmosts,
        sysinserttime,
        sysupdatetime
    FROM fact.sent_surveys AS ss
    WHERE ss.gem_syscosmosts > (SELECT ts FROM fact.watermarktable WHERE watermarktablename = 'fact.itemssurvey' AND source = 'gem')
      AND NOT EXISTS (SELECT 1 FROM fact.itemssurvey AS its 
                      WHERE its.locationid = ss.locationid
                        AND its.orderid = ss.orderid)
), flattened_survey_trxns AS (
    SELECT
        dss.organizationid,
        dss.locationid,
        dss.ordersessionid,
        dss.transactionheaderid,
        dss.gem_event_category,
        dss.gem_event_type,
        dss.orderid,
        TRIM(flat_survey.surveyid) AS surveyid,
        --TRIM(flat_item.itemid)     AS itemid,
        dss.is_responded,
        dss.gem_event_instant,
        dss.gem_syscosmosts,
        dss.sysinserttime,
        dss.sysupdatetime
    FROM delta_sent_surveys AS dss
    CROSS JOIN LATERAL (
        SELECT unnest(
            CASE WHEN dss.surveyid_array IS NOT NULL THEN ARRAY(SELECT jsonb_array_elements_text(dss.surveyid_array))
                 WHEN dss.surveyid_text  IS NOT NULL THEN string_to_array(dss.surveyid_text, ',')
            END
        ) AS surveyid
    ) AS flat_survey
    /*CROSS JOIN LATERAL (
        SELECT unnest(
            CASE WHEN dss.itemid_array IS NOT NULL THEN ARRAY(SELECT jsonb_array_elements_text(dss.itemid_array))
                 WHEN dss.itemid_text  IS NOT NULL THEN string_to_array(dss.itemid_text, ',')
            END
        ) AS itemid
    ) AS flat_item*/
), flattened_item_trxns AS (
    SELECT
        dss.organizationid,
        dss.locationid,
        dss.ordersessionid,
        dss.transactionheaderid,
        dss.gem_event_category,
        dss.gem_event_type,
        dss.orderid,
        --TRIM(flat_survey.surveyid) AS surveyid,
        TRIM(flat_item.itemid)     AS itemid,
        dss.is_responded,
        dss.gem_event_instant,
        dss.gem_syscosmosts,
        dss.sysinserttime,
        dss.sysupdatetime
    FROM delta_sent_surveys AS dss
    /*CROSS JOIN LATERAL (
        SELECT unnest(
            CASE WHEN dss.surveyid_array IS NOT NULL THEN ARRAY(SELECT jsonb_array_elements_text(dss.surveyid_array))
                 WHEN dss.surveyid_text  IS NOT NULL THEN string_to_array(dss.surveyid_text, ',')
            END
        ) AS surveyid
    ) AS flat_survey*/
    CROSS JOIN LATERAL (
        SELECT unnest(
            CASE WHEN dss.itemid_array IS NOT NULL THEN ARRAY(SELECT jsonb_array_elements_text(dss.itemid_array))
                 WHEN dss.itemid_text  IS NOT NULL THEN string_to_array(dss.itemid_text, ',')
            END
        ) AS itemid
    ) AS flat_item

), joined_surveys_with_items AS (
    SELECT st.organizationid,
           st.locationid,
           st.ordersessionid,
           st.transactionheaderid,
           st.gem_event_category,
           st.gem_event_type,
           st.orderid,
           st.surveyid,
           it.itemid,
           st.is_responded,
           st.gem_event_instant,
           st.gem_syscosmosts,
           st.sysinserttime,
           st.sysupdatetime 
           --ti.dimmenuitemid as menuitemid
    FROM flattened_survey_trxns as st 
    LEFT JOIN flattened_item_trxns as it
        ON st.locationid = it.locationid
        AND st.transactionheaderid = it.transactionheaderid
)
INSERT INTO temp_delta_sent_surveys
SELECT * FROM joined_surveys_with_items;


INSERT INTO fact.itemssurvey (
    organizationid,
    locationid,
    ordersessionid,
    orderid,
    surveyissuedtimestamp,
    gem_event_category,
    gem_event_type,
    surveyid,
    is_responded,
    gem_event_instant,
    gem_syscosmosts,
    sysinserttime,
    sysupdatetime,
    itemid
)
SELECT
    organizationid,
    locationid,
    ordersessionid,
    transactionheaderid,
    CASE WHEN substring(gem_event_instant, 20, 1) = '.' 
         THEN replace(replace(substring(gem_event_instant, 1, 23), 'T', ' '), '+', '0') 
         ELSE replace(substring(gem_event_instant, 1, 19), 'T', ' ') 
    END AS surveyissuedtimestamp,
    gem_event_category,
    gem_event_type,
    surveyid,
    is_responded,
    gem_event_instant,
    gem_syscosmosts,
    sysinserttime,
    sysupdatetime,
    itemid
FROM temp_delta_sent_surveys as tds
WHERE NOT EXISTS (SELECT * FROM fact.itemssurvey as its 
                  WHERE its.organizationid = tds.organizationid
                    AND its.locationid = tds.locationid
                    AND its.orderid = tds.transactionheaderid
                    AND its.itemid = tds.menuitemid
                    AND its.surveyid = tds.surveyid);


UPDATE fact.watermarktable
SET ts = (SELECT coalesce(max(gem_syscosmosts), 1775002010) - 10 FROM fact.itemssurvey)
WHERE watermarktablename = 'fact.itemssurvey'
  AND source = 'gem';


END;
$BODY$;

ALTER PROCEDURE fact.usp_sent_surveys_to_fact_itemssurvey()
OWNER TO citus;



UPDATE fact.watermarktable
SET ts = (SELECT coalesce(max(nge_syscosmosts), 1775002010) - 10 FROM fact.itemssurvey)
WHERE watermarktablename = 'fact.itemssurvey'
  AND source = 'nge';

UPDATE fact.itemssurvey
SET surveyissuedtimestamp =
    CASE WHEN substring(gem_event_instant, 20, 1) = '.' 
         THEN replace(replace(substring(gem_event_instant, 1, 23), 'T', ' '), '+', '0') 
         ELSE replace(substring(gem_event_instant, 1, 19), 'T', ' ') END
WHERE gem_event_instant IS NOT NULL;


SELECT * FROM fact.watermarktable LIMIT 100;
SELECT * FROM dim.feedbackstatus;
SELECT * FROM dim.feedbackrating;
SELECT * FROM dim.occasionsurvey LIMIT 100;
SELECT * FROM fact.occasionsurveydetail LIMIT 100;
SELECT * FROM fact.sent_surveys LIMIT 100;
SELECT * FROM fact.itemssurvey LIMIT 1000;
SELECT * FROM fact.transactionheader as th WHERE th.orderid = 'ordevt-0SK2SCECDID5KO9L' LIMIT 1000;


UPDATE fact.occasionsurveydetail
SET ordersessionid = th.ordersessionid
    --surveytype = CASE WHEN surveyrating ~ '^-?\d+$' THEN 1 ELSE 2 END; --number-based feedback = 1; text-based feedback = 2
FROM fact.transactionheader as th 
WHERE occasionsurveydetail.locationid = th.locationid
  AND occasionsurveydetail.orderid = th.transactionheaderid

UPDATE fact.itemssurvey
SET ordersessionid = th.ordersessionid
    --surveytype = CASE WHEN surveyrating ~ '^-?\d+$' THEN 1 ELSE 2 END; --number-based feedback = 1; text-based feedback = 2
FROM fact.transactionheader as th 
WHERE itemssurvey.locationid = th.locationid
  AND itemssurvey.orderid = th.transactionheaderid
  AND itemssurvey.ordersessionid IS NULL

SELECT locationid, orderid, surveyid, itemid, count(*)
FROM fact.itemssurvey
GROUP BY locationid, orderid, surveyid, itemid
HAVING count(*) > 1




--DELETE-- FROM stg.sent_surveys --itemssurvey
--WHERE orderid LIKE 'abort-%';

SELECT *-- orderid, surveytransid, surveyrating, surveytype, surveytransstatus, syscosmosts, sysinserttime
FROM fact.occasionsurveydetail
WHERE syscosmosts is NOT NULL
ORDER BY syscosmosts DESC;

SELECT *-- orderid, surveytransid, surveyrating, surveytype, surveytransstatus, syscosmosts, sysinserttime
FROM fact.itemssurvey
WHERE sysinserttime is NOT NULL
ORDER BY sysinserttime DESC;

SELECT * FROM fact.transactionheader as th WHERE th.transactionheaderid = 'ordevt-ZKZU1UN7E4CS30UT'

/*
create table dim.feedbackstatus
(surveytransstatus text COLLATE pg_catalog."default", statusdesc text COLLATE pg_catalog."default");
ALTER TABLE dim.feedbackstatus OWNER to citus;

create table dim.feedbackrating
(rating text COLLATE pg_catalog."default", ratingdesc text COLLATE pg_catalog."default");
ALTER TABLE dim.feedbackrating OWNER to citus;

select * from dim.occasionsurvey;*/

/*insert into fact.occasionsurveydetail(organizationid,locationid,dateid,surveyid,
surveytransid,orderid,surveyrating,surveytransstatus,surveyissuedtimestamp,
surveycompletedtimestamp,sysinserttime)*/
SELECT * from dim.feedbackstatus;
SELECT * FROM dim.feedbackrating;
SELECT * FROM dim.occasionsurvey LIMIT 100;
SELECT * FROM fact.occasionsurveydetail LIMIT 100;
SELECT * FROM fact.itemssurvey LIMIT 100;

select --th.ordersessionid, 
       osd.* 
from fact.occasionsurveydetail as osd--_bkp; as osd
/*INNER JOIN fact.transactionheader as th 
        ON osd.locationid = th.locationid
       AND osd.orderid = th.transactionheaderid
       AND osd.surveytransstatus = '1'*/
WHERE locationid = 'loc-56db8917-3e54-4be9-941b-5d2d4a5a4c22'
ORDER BY surveycompletedtimestamp DESC

SELECT * FROM fact.watermarktable
/*insert into fact.itemssurvey(organizationid,locationid,dateid,surveyid,
surveytransid,orderid,itemid,itemrating,surveytransstatus,surveyissuedtimestamp,
surveycompletedtimestamp,sysinserttime)*/
select *-- locationid, surveytransid, orderid, itemid, count(*) --* 
from fact.itemssurvey--_bkp
where 1=1
--and locationid = 'loc-af65011d-47ad-4043-b270-f81b30237ce9' 
--and dateid between 2025012000 and 2025012023
--and itemid = 'itm-4daa1cd4-c14b-49b9-9156-0a6f778827a8'-- 'itm-9b684758-d970-4eeb-b230-1ea24b384295'
--and orderid = 'ord-AAASLMQR9QAE'
--group by locationid, surveytransid, orderid, itemid
order by surveycompletedtimestamp desc;

select max(surveycompletedtimestamp) as maxdatetsinserted from fact.itemssurvey
select * from dim.feedbackstatus;
select * from dim.feedbackrating;

select ol.organizationid, its.* 
from fact.itemssurvey as its
inner join dim.organizationlocation as ol
on its.locationid = ol.locationid and ol.organizationtype = 0;

--update fact.itemssurvey
--set organizationid = ol.organizationid
--from dim.organizationlocation as ol
--where itemssurvey.locationid = ol.locationid and ol.organizationtype = 0;

select * from dim.organizationlocation as ol 
where ol.organizationtype = 0

SELECT
     od.surveytransid as Id,
     od.locationid as LocationId,
     od.dateid as DateId,
     od.surveytransstatus as SurveyTransStatus,
     od.orderid as OrderId,
     od.surveyrating as Rating,
     dd.datets as DateTs,
     dd.hourofday as HourOfDay,
     dd.dayval as DayVal,
     dd.dayname as DayName,
     dd.yearval as YearVal,
     dd.daypart as DayPart,
     dd.dayofyear as DayOfYear
 FROM fact.occasionsurveydetail od
 INNER JOIN dim.datedim AS dd ON dd.dateid = od.dateid
 INNER JOIN dim.organizationlocation as ol ON ol.locationid = od.locationid
 WHERE ol.organizationid = 'loc-9dbd4815-f50a-4e4f-ac1d-5fd6d9ec728e'
     AND dd.datets::DATE BETWEEN '2025-01-01'::TIMESTAMP AND '2025-08-13'::TIMESTAMP
	 AND od.surveytransstatus = '2'


select *, cast(to_char(surveylocaltimestamp, 'YYYYMMDDHH24') as INTEGER)
from fact.occasionsurveydetail


/*update fact.occasionsurveydetail
set surveylocaltimestamp = surveycompletedtimestamp::TIMESTAMPTZ AT TIME ZONE l.timezone
from (select distinct locationid, case when timezone is null or timezone='' then 'America/New_York' else timezone end as timezone from dim.location) as l
where occasionsurveydetail.locationid = l.locationid
  and occasionsurveydetail.surveylocaltimestamp is null;

update fact.occasionsurveydetail
set surveylocaltimestamp = surveycompletedtimestamp::TIMESTAMPTZ AT TIME ZONE 'America/New_York'
where surveylocaltimestamp is null;

update fact.itemssurvey
set surveylocaltimestamp = surveycompletedtimestamp::TIMESTAMPTZ AT TIME ZONE l.timezone
from (select distinct locationid, case when timezone is null or timezone='' then 'America/New_York' else timezone end as timezone from dim.location) as l
where itemssurvey.locationid = l.locationid
  and itemssurvey.surveylocaltimestamp is null;

update fact.itemssurvey
set surveylocaltimestamp = surveycompletedtimestamp::TIMESTAMPTZ AT TIME ZONE 'America/New_York'
where surveylocaltimestamp is null;

update fact.occasionsurveydetail
set dateid = cast(to_char(surveylocaltimestamp, 'YYYYMMDDHH24') as INTEGER)
where dateid is null;

update fact.itemssurvey
set dateid = cast(to_char(surveylocaltimestamp, 'YYYYMMDDHH24') as INTEGER)
where dateid is null;*/
