drop table if exists dim.occasionsurvey;
CREATE TABLE IF NOT EXISTS dim.occasionsurvey
(
    surveykey bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    organizationid text COLLATE pg_catalog."default" NOT NULL,
    surveyid text COLLATE pg_catalog."default" NOT NULL,
    surveyname text COLLATE pg_catalog."default",
    surveytype text COLLATE pg_catalog."default",
    CONSTRAINT survey_pkey PRIMARY KEY (surveykey)
)

TABLESPACE pg_default;

ALTER TABLE dim.occasionsurvey
    OWNER to citus;

--drop table if EXISTS fact.itemssurvey;
CREATE TABLE IF NOT EXISTS fact.itemssurvey
(
    organizationid text COLLATE pg_catalog."default",
    locationid text COLLATE pg_catalog."default",
    dateid integer,
    surveyid text COLLATE pg_catalog."default",
    surveytransid text COLLATE pg_catalog."default",
    orderid text COLLATE pg_catalog."default",
    itemid text COLLATE pg_catalog."default",
    itemrating text COLLATE pg_catalog."default",
    surveytransstatus text COLLATE pg_catalog."default",
    surveyissuedtimestamp text COLLATE pg_catalog."default",
    surveycompletedtimestamp text COLLATE pg_catalog."default",
    surveylocaltimestamp timestamp,
    sysinserttime timestamp
)

TABLESPACE pg_default;

ALTER TABLE fact.itemssurvey
    OWNER to citus;

--drop TABLE IF EXISTS fact.occasionsurveydetail;
CREATE TABLE IF NOT EXISTS fact.occasionsurveydetail
(
    organizationid text COLLATE pg_catalog."default",
    locationid text COLLATE pg_catalog."default",
    dateid integer,
    surveyid text COLLATE pg_catalog."default",
    surveytransid text COLLATE pg_catalog."default",
    orderid text COLLATE pg_catalog."default",
    surveyrating text COLLATE pg_catalog."default",
    surveytransstatus text COLLATE pg_catalog."default",
    surveyissuedtimestamp text COLLATE pg_catalog."default",
    surveycompletedtimestamp text COLLATE pg_catalog."default",
    surveylocaltimestamp timestamp,
    sysinserttime timestamp without time zone
)

TABLESPACE pg_default;

ALTER TRUNCATE TABLE fact.occasionsurveydetail
    OWNER to citus;

CREATE TABLE IF NOT EXISTS stg.sent_surveys
(
    organizationid text COLLATE pg_catalog."default",
    locationid text COLLATE pg_catalog."default",
    ordersessionid TEXT COLLATE pg_catalog."default",
    orderid TEXT COLLATE pg_catalog."default",
    gem_event_category TEXT COLLATE pg_catalog."default",
    gem_event_type TEXT COLLATE pg_catalog."default",
    survey_metadata TEXT COLLATE pg_catalog."default",
    is_responded BOOLEAN,
    gem_event_instant TEXT COLLATE pg_catalog."default",
    gem_syscosmosts BIGINT,
    sysinserttime TIMESTAMP,
    sysupdatetime TIMESTAMP,
    CONSTRAINT sent_surveys_ordersessionid_pkey PRIMARY KEY (ordersessionid)
)

TABLESPACE pg_default;

ALTER TABLE stg.sent_surveys
    OWNER to citus;

ALTER TABLE stg.sent_surveys
ADD COLUMN IF NOT EXISTS orderid TEXT COLLATE pg_catalog."default";

ALTER TABLE fact.occasionsurveydetail
--DROP COLUMN ngesyscosmosts,
--DROP COLUMN gemsyscosmosts
--add syscosmosts BIGINT--- ngesyscosmosts BIGINT, add gemsyscosmosts BIGINT,
ADD COLUMN IF NOT EXISTS surveytype INTEGER, --number-based feedback = 1; text-based feedback = 2
ADD COLUMN IF NOT EXISTS ordersessionid TEXT COLLATE pg_catalog."default"

ALTER TABLE fact.itemssurvey
ADD COLUMN IF NOT EXISTS nge_syscosmosts BIGINT,
ADD COLUMN IF NOT EXISTS ordersessionid TEXT COLLATE pg_catalog."default",
ADD COLUMN IF NOT EXISTS gem_event_category TEXT COLLATE pg_catalog."default",
ADD COLUMN IF NOT EXISTS gem_event_type TEXT COLLATE pg_catalog."default",
ADD COLUMN IF NOT EXISTS is_responded BOOLEAN,
ADD COLUMN IF NOT EXISTS gem_syscosmosts BIGINT,
ADD COLUMN IF NOT EXISTS gem_event_instant TEXT COLLATE pg_catalog."default",
ADD COLUMN IF NOT EXISTS sysupdatetime TIMESTAMP,
ADD COLUMN IF NOT EXISTS source SMALLINT;

SELECT orderid, itemid, count(*)
FROM fact.itemssurvey --LIMIT 100
GROUP BY orderid, itemid
HAVING count(*) > 1

CREATE OR REPLACE PROCEDURE fact.usp_gem_sent_surveys_to_fact()
LANGUAGE plpgsql
AS $BODY$

BEGIN

WITH delta_sent_surveys AS (
SELECT
FROM stg.sent_surveys as ss
WHERE ss.syscosmosts > (SELECT ts FROM fact.watermarktable WHERE watermarktablename = 'fact.itemssurvey' AND source = 'gem')
  AND NOT EXISTS (SELECT 1 FROM fact.itemssurvey as its 
                  WHERE its.locationid = ss.locationid
                    AND its.orderid = ss.orderid)
), get_surveyids AS (
SELECT 
FROM delta_sent_surveys as ds
WHERE
)

END;

$BODY$


SELECT * FROM dim.feedbackstatus;
SELECT * FROM dim.feedbackrating;
SELECT * FROM dim.occasionsurvey LIMIT 100;
SELECT * FROM fact.occasionsurveydetail LIMIT 100;
SELECT * FROM fact.itemssurvey LIMIT 100;


UPDATE fact.occasionsurveydetail
SET ordersessionid = th.ordersessionid
    --surveytype = CASE WHEN surveyrating ~ '^-?\d+$' THEN 1 ELSE 2 END; --number-based feedback = 1; text-based feedback = 2
FROM fact.transactionheader as th 
WHERE occasionsurveydetail.locationid = th.locationid
  AND occasionsurveydetail.orderid = th.transactionheaderid


SELECT *-- orderid, surveytransid, surveyrating, surveytype, surveytransstatus, syscosmosts, sysinserttime
FROM fact.occasionsurveydetail
WHERE syscosmosts is NOT NULL
ORDER BY syscosmosts DESC;

SELECT *-- orderid, surveytransid, surveyrating, surveytype, surveytransstatus, syscosmosts, sysinserttime
FROM fact.itemssurvey
WHERE sysinserttime is NOT NULL
ORDER BY sysinserttime DESC;

SELECT * FROM fact.transactionheader th WHERE th.transactionheaderid = 'ordevt-ZKZU1UN7E4CS30UT'

/*
create table dim.feedbackstatus
(surveytransstatus text COLLATE pg_catalog."default", statusdesc text COLLATE pg_catalog."default");
ALTER TABLE dim.feedbackstatus OWNER to citus;

create table dim.feedbackrating
(rating text COLLATE pg_catalog."default", ratingdesc text COLLATE pg_catalog."default");
ALTER TABLE dim.feedbackrating OWNER to citus;

select * from dim.occasionsurvey;*/

/*insert into fact.occasionsurveydetail(organizationid,locationid,dateid,surveyid,
surveytransid,orderid,surveyrating,surveytransstatus,surveyissuedtimestamp,
surveycompletedtimestamp,sysinserttime)*/
SELECT * from dim.feedbackstatus;
SELECT * FROM dim.feedbackrating;
SELECT * FROM dim.occasionsurvey LIMIT 100;
SELECT * FROM fact.occasionsurveydetail LIMIT 100;
SELECT * FROM fact.itemssurvey LIMIT 100;

select --th.ordersessionid, 
       osd.* 
from fact.occasionsurveydetail as osd--_bkp; as osd
/*INNER JOIN fact.transactionheader as th 
        ON osd.locationid = th.locationid
       AND osd.orderid = th.transactionheaderid
       AND osd.surveytransstatus = '1'*/
WHERE locationid = 'loc-56db8917-3e54-4be9-941b-5d2d4a5a4c22'
ORDER BY surveycompletedtimestamp DESC

SELECT * FROM fact.watermarktable
/*insert into fact.itemssurvey(organizationid,locationid,dateid,surveyid,
surveytransid,orderid,itemid,itemrating,surveytransstatus,surveyissuedtimestamp,
surveycompletedtimestamp,sysinserttime)*/
select *-- locationid, surveytransid, orderid, itemid, count(*) --* 
from fact.itemssurvey--_bkp
where 1=1
--and locationid = 'loc-af65011d-47ad-4043-b270-f81b30237ce9' 
--and dateid between 2025012000 and 2025012023
--and itemid = 'itm-4daa1cd4-c14b-49b9-9156-0a6f778827a8'-- 'itm-9b684758-d970-4eeb-b230-1ea24b384295'
--and orderid = 'ord-AAASLMQR9QAE'
--group by locationid, surveytransid, orderid, itemid
order by surveycompletedtimestamp desc;

select max(surveycompletedtimestamp) as maxdatetsinserted from fact.itemssurvey
select * from dim.feedbackstatus;
select * from dim.feedbackrating;

select ol.organizationid, its.* 
from fact.itemssurvey as its
inner join dim.organizationlocation as ol
on its.locationid = ol.locationid and ol.organizationtype = 0;

--update fact.itemssurvey
--set organizationid = ol.organizationid
--from dim.organizationlocation as ol
--where itemssurvey.locationid = ol.locationid and ol.organizationtype = 0;

select * from dim.organizationlocation as ol 
where ol.organizationtype = 0

SELECT
     od.surveytransid as Id,
     od.locationid as LocationId,
     od.dateid as DateId,
     od.surveytransstatus as SurveyTransStatus,
     od.orderid as OrderId,
     od.surveyrating as Rating,
     dd.datets as DateTs,
     dd.hourofday as HourOfDay,
     dd.dayval as DayVal,
     dd.dayname as DayName,
     dd.yearval as YearVal,
     dd.daypart as DayPart,
     dd.dayofyear as DayOfYear
 FROM fact.occasionsurveydetail od
 INNER JOIN dim.datedim AS dd ON dd.dateid = od.dateid
 INNER JOIN dim.organizationlocation as ol ON ol.locationid = od.locationid
 WHERE ol.organizationid = 'loc-9dbd4815-f50a-4e4f-ac1d-5fd6d9ec728e'
     AND dd.datets::DATE BETWEEN '2025-01-01'::TIMESTAMP AND '2025-08-13'::TIMESTAMP
	 AND od.surveytransstatus = '2'


select *, cast(to_char(surveylocaltimestamp, 'YYYYMMDDHH24') as INTEGER)
from fact.occasionsurveydetail


/*update fact.occasionsurveydetail
set surveylocaltimestamp = surveycompletedtimestamp::TIMESTAMPTZ AT TIME ZONE l.timezone
from (select distinct locationid, case when timezone is null or timezone='' then 'America/New_York' else timezone end as timezone from dim.location) as l
where occasionsurveydetail.locationid = l.locationid
  and occasionsurveydetail.surveylocaltimestamp is null;

update fact.occasionsurveydetail
set surveylocaltimestamp = surveycompletedtimestamp::TIMESTAMPTZ AT TIME ZONE 'America/New_York'
where surveylocaltimestamp is null;

update fact.itemssurvey
set surveylocaltimestamp = surveycompletedtimestamp::TIMESTAMPTZ AT TIME ZONE l.timezone
from (select distinct locationid, case when timezone is null or timezone='' then 'America/New_York' else timezone end as timezone from dim.location) as l
where itemssurvey.locationid = l.locationid
  and itemssurvey.surveylocaltimestamp is null;

update fact.itemssurvey
set surveylocaltimestamp = surveycompletedtimestamp::TIMESTAMPTZ AT TIME ZONE 'America/New_York'
where surveylocaltimestamp is null;

update fact.occasionsurveydetail
set dateid = cast(to_char(surveylocaltimestamp, 'YYYYMMDDHH24') as INTEGER)
where dateid is null;

update fact.itemssurvey
set dateid = cast(to_char(surveylocaltimestamp, 'YYYYMMDDHH24') as INTEGER)
where dateid is null;*/
